//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryView
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> VIODemand { get; set; }
        public Nullable<int> MarketPotential { get; set; }
        public Nullable<decimal> Customer_12M_Sales { get; set; }
        public Nullable<decimal> Market_Share__ { get; set; }
        public string CountryStr { get; set; }
        public string CurrencyStr { get; set; }
    }
}
