//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorPrice
    {
        public long Id { get; set; }
        public long RefID { get; set; }
        public decimal PriceValue { get; set; }
        public int PriceTypeID { get; set; }
        public System.DateTime PriceDate { get; set; }
        public int CountryId { get; set; }
        public int CurrencyId { get; set; }
    }
}
