//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelViewAgeDistribution
    {
        public int ID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MarketPotential { get; set; }
        public Nullable<int> VIODemand { get; set; }
        public string CountryStr { get; set; }
        public string CurrencyStr { get; set; }
        public string Category { get; set; }
    }
}
