//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsPotentialCategory
    {
        public int ID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<decimal> Database_ { get; set; }
        public Nullable<int> PartCount { get; set; }
        public Nullable<decimal> RevCoverage { get; set; }
        public Nullable<decimal> MarketShare_ { get; set; }
        public string CountryStr { get; set; }
        public string CurrencyStr { get; set; }
    }
}
