//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsPotentialVIOCoverageBrandGlobal
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public Nullable<decimal> Distribution_ { get; set; }
        public Nullable<int> VIOCoverage { get; set; }
        public string CountryStr { get; set; }
        public string CurrencyStr { get; set; }
    }
}
