//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartsPotentialDashboard
    {
        public int ID { get; set; }
        public string Dashboard { get; set; }
        public Nullable<int> VIOCoverage { get; set; }
        public Nullable<int> MarketPotential { get; set; }
        public Nullable<int> PartGroup { get; set; }
        public Nullable<int> PartNumber { get; set; }
        public Nullable<int> VehicleCount { get; set; }
        public Nullable<decimal> RevenueCoverage { get; set; }
        public Nullable<decimal> MarketShare { get; set; }
        public string CountryStr { get; set; }
        public string CurrencyStr { get; set; }
    }
}
