//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceData
    {
        public long PartID { get; set; }
        public string Partnumber { get; set; }
        public string Wholesaler { get; set; }
        public string Brand { get; set; }
        public string PartDescription { get; set; }
    }
}
