//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_IntelligenceViewData
    {
        public long ID { get; set; }
        public string CountryStr { get; set; }
        public string Country { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<long> CustomerPartId { get; set; }
        public string PartNo { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string VehicleName { get; set; }
        public Nullable<decimal> List_Price { get; set; }
        public Nullable<decimal> ACP_Online_Price { get; set; }
        public Nullable<decimal> NET_Price { get; set; }
        public Nullable<decimal> Core_Price { get; set; }
        public Nullable<decimal> Installer_Price { get; set; }
        public Nullable<decimal> OEMAvgList_Price { get; set; }
        public Nullable<decimal> OEMAvgACP_Online_Price { get; set; }
        public Nullable<decimal> OEMAvgNET_Price { get; set; }
        public Nullable<decimal> OEMAvgCore_Price { get; set; }
        public Nullable<decimal> OEMAvgInstaller_Price { get; set; }
        public Nullable<decimal> IAMAvgList_Price { get; set; }
        public Nullable<decimal> IAMAvgACP_Online_Price { get; set; }
        public Nullable<decimal> IAMAvgNET_Price { get; set; }
        public Nullable<decimal> IAMAvgCore_Price { get; set; }
        public Nullable<decimal> IAMAvgInstaller_Price { get; set; }
        public Nullable<int> VIO_Demand { get; set; }
        public Nullable<int> Market_Potential { get; set; }
        public Nullable<decimal> Market_Share { get; set; }
        public Nullable<decimal> Customer_12M_Sales { get; set; }
        public Nullable<decimal> OEM_Price_Trend { get; set; }
        public Nullable<decimal> IAM_Price_Trend { get; set; }
        public Nullable<decimal> VIO_Demand_Trend { get; set; }
        public Nullable<decimal> Market_Potential_Trend { get; set; }
        public Nullable<decimal> Market_Share_Trend { get; set; }
        public Nullable<decimal> Customer_12M_Sales_Trend { get; set; }
        public string CurrencyStr { get; set; }
    }
}
