//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHIAppConfig
    {
        public long Id { get; set; }
        public string DBString { get; set; }
        public string Condition { get; set; }
        public string ConditionValue { get; set; }
    }
}
